cpojer/js-codemod

- test/no-vars-test.js
- test/no-vars-test.output.js
- transforms/no-vars.js
This is a first pass at making no-vars safe.  I believe it handles
pretty much all the cases where `var` behaves oddly, by just leaving
them as `var`.  I didn't make it separate out `let` and `const` when
they were mixed in a single `var` declaration, but I can add that in if
desired.  I also didn't implement the behaviour of converting multiple
for loops that reuse a variable into `let` as it seemed highly complex
to get right.  I've added some TODOs for that though.
> Make a safe version of no-vars

- test/no-vars-test.js
- test/no-vars-test.output.js
- transforms/no-vars.js
We didn't look inside functions for odd usage of variables, but we
really should have done, because if the function doesn't declare that
variable, things get weird.
> Fix another edge case

- README.md
- extensions/imports/README.md
- extensions/imports/__tests__/addImportCJSBasicConfig-test.js
- extensions/imports/__tests__/addImportFBConfig-test.js
- extensions/imports/addImport.js
- extensions/imports/config/CJSBasicRequireConfig.js
- extensions/imports/config/FBRequireConfig.js
- extensions/imports/index.js
- extensions/imports/utils/getDeclarationName.js
- extensions/imports/utils/isValidRequireDeclaration.js
- package.json
The purpose of this is to create a jscodeshift extension that can add requires in a non destructive manner, it doesn't try to have the requires be perfect it just tries to make the best guess at where it should go. I have based a lot of this work from js-format (in fact most of utils is directly copied from here) with the difference in this is non destructive to existing code.
Currently not all the tests pass as i am having some issues with whitespace printing, and i have also not implemented the feature to constraint the require adding to just the first relevant block.
the API looks like this:
```javascript
const plugins = imports.register(jscodeshift, imports.config.CJSBasicRequire);
jscodeshift(file.source)
.addImport(statement`
import MyImportItem from './path/to/MyImportItem';
`)
// …
```
> [RFC] Add addImport extension

- README.md
- extensions/imports/README.md
- extensions/imports/package.json
I have called the extension `jscodeshift-imports` since it's specific to `jscodeshift`, or should it be `js-codemod-imports` since it's in that repo??
This adds the `package.json` + cleans up the docs a little.
> Make the imports extension its own package.

- transforms/no-vars.js
I noticed these warnings while running tests locally.
> Fix linter warnings in no-vars.js

- .eslintignore
- test/__tests__/invalid-requires-test.js
- test/invalid-requires-test.js
- test/invalid-requires-test.output.js
- transforms/invalid-requires.js
When converting a require block like:
```js
var foo = require('foo'),
// A comment
bar = require('bar');
```
this transform was producing the unusual output:
```js
var foo = require('foo');
var // A comment
bar = require('bar');
```
This commit fixes this by moving the comment from the require statement
declaration up to the variable declaration. It now produces the following:
```js
var foo = require('foo');
// A comment
var bar = require('bar');
```
> Teach invalid-requires to better handle comments

- test/invalid-requires-test.js
- test/invalid-requires-test.output.js
- transforms/invalid-requires.js
I noticed that this was always using `var` even if `const` was used
before the transform. This commit aims to preserve the kind that was
used.
> Preserve kind of variable declaration in invalid-requires

- test/__tests__/unchain-variables-test.js
- test/unchain-variables-test.js
- test/unchain-variables-test.output.js
- transforms/invalid-requires.js
- transforms/outline-require.js
- transforms/unchain-variables.js
This transform will unchain chained variable declarations. Converting
code like:
```js
var foo, bar;
```
to:
```js
var foo;
var bar;
```
> Add unchain-variables transform

- test/no-vars-test.js
- test/no-vars-test.output.js
- transforms/no-vars.js
While running this on Airbnb code, I ran into the following error:
> TypeError: Cannot read property 'type' of null
Which seemed to happen when encountering array destructuring with
ignored values, like:
```js
var [, foo, bar] = baz;
```
I fixed this by guarding against this case in a few places.
While I was at it, I also fixed some typos that I happened to notice.
> Teach no-vars about array destructuring with ignored values

- test/unchain-variables-test.js
- test/unchain-variables-test.output.js
- transforms/unchain-variables.js
When encountering a ForStatement, this would output an error complaining
that it was unable to replace the path. To prevent this, I added a
filter.
> Skip ForStatements when unchaining variables

- test/__tests__/trailing-commas-test.js
- test/trailing-commas-test.js
- test/trailing-commas-test.output.js
- transforms/trailing-commas.js
Transform to add dangling commas to allow enabling eslint dangling-commas always-multiline rule. It formats only arrays and objects that don't already have a dangling comma to keep changes as minimal as possible.
What I did is to find all the object/arrays that don't have a trailing comma and then add a random key to them so they are modified. Then in a second pass I remove the added keys and format using recast trailingComma option.
The end goal here would be to run that the on react-native codebase to enable stricter eslint rules without having to manually fix the 1k+ warnings it will generate :)
Tested against the react-native codebase pretty succesfully. The only thing it doesn't support that eslint complains about is trailing commas in destructuring. It should be pretty easy to add …
> Add dangling commas transform

- test/__tests__/trailing-commas-test.js
This test file was referencing dangling-commas and dangling-commas-test,
which don't exist.
> Fix trailing-commas test

- extensions/imports/__tests__/addImportCJSBasicConfig-test.js
- extensions/imports/__tests__/addImportFBConfig-test.js
- extensions/imports/addImport.js
- extensions/imports/config/CJSBasicRequireConfig.js
- extensions/imports/config/FBRequireConfig.js
- extensions/imports/index.js
- extensions/imports/utils/getDeclarationName.js
- extensions/imports/utils/isValidRequireDeclaration.js
Changes:
- remove object deconstruction
- add 'use strict'
Tested by removing the babel preprocessor from jest and running the tests :)
> Node compatibility for `imports` extenision.

- README.md
- test/trailing-commas-test.js
- test/trailing-commas-test.output.js
- transforms/trailing-commas.js
Simply setting the wrapColumn formatting option to 1 instead of 0 makes it not add new lines everywhere.
Also adds the transform to the readme.
Fixes #27
cc @lencioni @cpojer
> Fix trailing-commas transform with objects in function calls

- package.json
I moved the dependencies that are only used for linting or testing to the devDependencies section of the package.json. This is so that if this is included as a dependency of something else it does not bring in any excess baggage!
> move some dependencies to devDependencies

- transforms/__testfixtures__/no-vars.input.js
- transforms/__testfixtures__/no-vars.output.js
- transforms/no-vars.js
This PR fixes detection of `let`/ `const` in `for in` and `for of` loops. Before this, any declaration without an `init` was being handled as a `let`, which is still the correct handling of the generic `let foo;` case. However, `for in` and `for of` loops are special cases of declarations in that they have a kind of implicit initialization for each run of the loop. This PR detects this case and allows it to continue onto the "is this mutated?" stage of the process.
A bunch of tests fail and there are two linter warnings, but these appear to be on master, too.
cc/ @cpojer @pieterv @voideanvalue
cc/ @bouk
> Add proper const/ let decisions for for loops

- transforms/__testfixtures__/arrow-function.input.js
- transforms/__testfixtures__/arrow-function.output.js
- transforms/arrow-function.js
For the test, my main concern is that every comment in the input appears
somewhere in the output (even if the order changes).
Also, looks like there are two pre-existing test failures unrelated to `arrow-function`.
At least for me, all `arrow-function` tests pass, including my new cases.
> Change arrow-function to transfer comments from the old AST

- transforms/__testfixtures__/object-shorthand.input.js
- transforms/__testfixtures__/object-shorthand.output.js
- transforms/object-shorthand.js
Recursive methods should not be transformed to the shorthand.
> Fix recursive methods in object shorthand

- transforms/__testfixtures__/jest-remove-describe.input.js
- transforms/__testfixtures__/jest-remove-describe.output.js
- transforms/__tests__/jest-remove-describe-test.js
- transforms/jest-remove-describe.js
When there's only one describe block in a test file, we can safely remove it to remove noise.
> Add remove-describe transform

- transforms/__testfixtures__/flow-bool-to-boolean.input.js
- transforms/__testfixtures__/flow-bool-to-boolean.output.js
- transforms/__tests__/flow-bool-to-boolean-test.js
- transforms/flow-bool-to-boolean.js
It turns out that there's no difference between those two at the AST level. So I just replace it by the same thing which is going make it dirty and reprinted by recast with the correct one.
> Flow bool -> boolean

- transforms/__testfixtures__/jest-arrow.input.js
- transforms/__testfixtures__/jest-arrow.output.js
- transforms/__tests__/jest-arrow.js
- transforms/jest-arrow.js
```js
describe(function() {
it('should work', function() {
...
});
});
```
->
```js
describe(() => {
it('should work', () => {
...
});
});
```
> Add normal to arrow function transform for jest tests

- transforms/no-vars.js
- transforms/trailing-commas.js
es6 syntax `export default` were used in some transforms
this was causing errors in some circumstances
see https://github.com/cpojer/js-codemod/issues/60
> Fixed erroneous export syntax in some transforms

- extensions/imports/config/CJSBasicRequireConfig.js
- extensions/imports/config/FBRequireConfig.js
- extensions/imports/package.json
- extensions/imports/utils/isValidRequireDeclaration.js
- package.json
`nuclide-format-js-base` was replaced by `nuclide-format-js`, the code in 0.0.36 is the same as in 0.0.35, just in a different spot.
Test plan:
`npm test`.
cc: @cpojer
> nuclide-format-js-base -> nuclide-format-js

- transforms/__testfixtures__/jest-remove-disable-automock.input.js
- transforms/__testfixtures__/jest-remove-disable-automock.output.js
- transforms/__tests__/jest-remove-disable-automock-test.js
- transforms/jest-remove-disable-automock.js
This codemod transforms jest test files to remove instances of `.disableAutomock()` while preserving the rest of the function chain (ex. `jest.disableAutomock().mock('abc')` => `jest.mock('abc')`). It also removes any empty `jest;` statements left by the transform and preserves header comments if they would be stripped.
> add codemod to remove jest.disableAutomock()

- README.md
- transforms/__testfixtures__/rm-object-assign.input.js
- transforms/__testfixtures__/rm-object-assign.output.js
- transforms/__tests__/rm-object-assign-test.js
- transforms/rm-object-assign.js
I originally made this codemod for @doctolib but I think it's worth sharing with the community. Is it the right place to drop it?
> Add a codemod to favor object spread over `Object.assign`

- transforms/__testfixtures__/arrow-function-arguments.input.js
- transforms/__testfixtures__/arrow-function-arguments.output.js
- transforms/arrow-function-arguments.js
Otherwise it transforms to:
var fn7 = (ref, ...args) => console.log(ref.[ref, ...args]);
> arrow-function-arguments: filter identifiers in member expressions

- transforms/arrow-function.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_arguments
"Arrow functions do not have their own arguments object."
Therefore
```
function () { console.log(arguments); }
```
is not the same as
```
() => { console.log(arguments); }
```
> Do not transform functions using arguments object

- README.md
- transforms/__tests__/no-reassign-params-test.js
- transforms/no-reassign-params.js
Adding this codemod because someone from open source might be interested in fixing the shadowing issue that keeps us from using this at Facebook. 
A test for the issue we have at Facebook is commented out in the test file:
```
// Shadowing function argument
// This doesn't work yet and is the major blocker to us being able to
// use this at Facebook.
defineInlineTest(
transform,
undefined,
`
function foo(x) {
x = 2;
var x = 4;
return x;
}`,
`
function foo({x}) {
let localX = x;
localX = 2;
var localX2 = 4;
return localX2;
}`,
);
```
Reasonable to merge this in the mean time for others to get value. Most people don't run into this edge case.
> Add no-reassign-params

- extensions/imports/README.md
Link to `Basic commonJS style` and `Facebook style` was not relative, and therefore did not work.
> Fix relativ path usage in imports readme

- transforms/unquote-properties.js
Strings that coerce into number representations different from themselves (e.g. `'0x04'`, `'0o42'`, `'0b100'`, `'08'`) should be ignored.
> Ignore coerced numbers

- transforms/arrow-function.js
```javascript
[].forEach(function() {
return;
});
```
This errors on `arrow-function.js` because there was no logic to handle the useless `return`.
> Fix error for function with only a return.

- transforms/__testfixtures__/arrow-function.input.js
- transforms/__testfixtures__/arrow-function.output.js
- transforms/arrow-function.js
I noticed that anonymous generator functions are getting transformed to arrow functions, with the output resulting in a different type of function altogether. An example of the input & output can be seen [here](https://astexplorer.net/#/gist/fcf7ab3025c4857a5879fef90df56504/b6111c138a5da7e25bab23111fa398bcdacdcf6a).
This PR changes the arrow-function.js codemod to transform non-generator functions only.
> Don't transform generator functions to arrow
